services:
  # Project
  nest-demo:
    container_name: gzhu_library_booking
    build:
      dockerfile: Dockerfile
    ports:
      - '8888:8888'
    networks:
      - mysql
    depends_on:
      - mysql

  # MySQL
  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    networks:
      - mysql
    volumes:
      - mysql:/var/lib/mysql:rw
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gzhu_library_booking

networks:
  mysql:

volumes:
  mysql:
